name: Test examples

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ['pca10056', 'feather52840']

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive      
        
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1

    - name: Install BSP and Libraries
      env:
        BSP_URL: https://github.com/jpconstantineau/Community_nRF52_Arduino/releases/latest/download/package_jpconstantineau_boards_index.json
        BSP_PATH: .arduino15/packages/community_nrf52/hardware/nrf52
        BSP_URL_ADA: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
        BSP_PATH_ADA: .arduino15/packages/adafruit/hardware/nrf52
      run: |
        pip3 install adafruit-nrfutil
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core update-index --additional-urls $BSP_URL_ADA
        arduino-cli core install adafruit:nrf52 --additional-urls $BSP_URL_ADA
        arduino-cli core update-index --additional-urls $BSP_URL
        arduino-cli core install community_nrf52:nrf52 --additional-urls $BSP_URL
        arduino-cli core list
        arduino-cli board listall

        # Replace release BSP with our code
        BSP_VERSION=`eval ls $HOME/$BSP_PATH`
        rm -r $HOME/$BSP_PATH/*
        ln -s $GITHUB_WORKSPACE $HOME/$BSP_PATH/$BSP_VERSION

        # Library summary
        arduino-cli lib list

    - name: Build examples
      run: echo python3 tools/build_all.py ${{ matrix.arduino-platform }}
